package com.sunil.data.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ARTICLE".
 */
@Entity
public class Article {

    @Id
    private Long id;

    @NotNull
    private String tittle;
    private String description;
    private String author;

    @Generated(hash = 742516792)
    public Article() {
    }

    public Article(Long id) {
        this.id = id;
    }

    @Generated(hash = 1840305709)
    public Article(Long id, @NotNull String tittle, String description, String author) {
        this.id = id;
        this.tittle = tittle;
        this.description = description;
        this.author = author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getTittle() {
        return tittle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTittle(@NotNull String tittle) {
        this.tittle = tittle;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

}
